### ISSUE TITLE
need function equivalent to "add_special_tokens"

### ISSUE THREAD

**Issue by parsifal9** [bnosac/tokenizers.bpe#4]
HI bnosac,

I need to add some special tokens (as below). There is no function to do this. Is there a workaround?
```
tokenizer <- bpe_load_model(tokenizer_file)
tokenizer$add_special_tokens(list(pad_token = "[PAD]"))
Error: attempt to apply non-function
```
Bye

**Comment by jwijffels** [comment]
Function bpe has arguments pad_id = 0L, unk_id = 1L, bos_id = 2L, eos_id = 3L, is that what you are looking for?

**Comment by parsifal9** [comment]
Hi jwijffels,

sorry, I was totally confused about this, and wasted your time.
Getting the PAD token into the tokenizer was actually the least of my problems. 
 The file I was trying to load was actually in JSON. 
I am closing this issue cos the real issue was my confusion.
Bye
